# Generated by Django 4.2.11 on 2026-01-13 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="experiencebooking",
            name="agreement_accepted",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="experiencebooking",
            name="date_signed",
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="experiencebooking",
            name="event_service_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experiencebooking",
            name="event_service_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="experiencebooking",
            name="first_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="experiencebooking",
            name="last_name",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="experiencebooking",
            name="special_requests",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="experiencebooking",
            name="time_slot",
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name="experiencebooking",
            name="customer_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="experiencebooking",
            name="customer_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
